In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim 

torch.manual_seed(1)

In [5]:
V_data = [1, 2, 3]
V = torch.tensor(V_data)
print(V.size())

M_data = [[1, 2, 3], [1, 2, 3]]
M = torch.tensor(M_data)
print(M.size())

T_data = [[[1, 2], [1, 2]], [[2, 2], [3, 3]]]
T = torch.tensor(T_data)
print(T.size())

torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 2])


In [7]:
print(V[0])
print(V[0].item())
print(M[0])
print(T[0])

tensor(1)
1
tensor([ 1,  2,  3])
tensor([[ 1,  2],
        [ 1,  2]])


In [8]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x + y
print(z)

tensor([ 5,  7,  9])


In [9]:
# Tensor factory methods have a ``requires_grad`` flag
x = torch.tensor([1., 2., 3], requires_grad=True)

# With requires_grad=True, you can still do all the operations you previously
# could
y = torch.tensor([4., 5., 6], requires_grad=True)
z = x + y
print(z)

# BUT z knows something extra.
print(z.grad_fn)

tensor([ 5.,  7.,  9.])


In [11]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21.)


In [12]:
print(x.grad)
s.backward()
print(x.grad)


None
tensor([ 1.,  1.,  1.])


In [13]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

False False
None
True
None
